### PR TITLE
Storage format

### PR DESCRIPTION
**Pull request by charlesoblack**
I just decided to save as JSON for now. It also saves the board width/height. The tensor in `board_state` should be binary.

It also abuses some (hopeful) API for the `Game` class that has `width`, `height`, `board_state` as properties and a constructor `from_json` that can read the json dict and create a game of that kind with the appropriate params.

### CODE REVIEW

**Comment by PhilipEkfeldt** [comment]
Looks good. Only question, does the game object here represent a game rule set or an game instance state?

**Comment by charlesoblack** [comment]
It should be an instance of a game, so a specific game. Otherwise there couldn't be a board state for it :P

**Comment by PhilipEkfeldt** [comment]
> It should be an instance of a game, so a specific game. Otherwise there couldn't be a board state for it :P

Right, I was just thinking it could be a starting state. :P

**Comment by charlesoblack** [comment]
Ah, I see what you mean. I'm mostly styling this along the lines of the `python-chess` library because I think it has some great things about it. [Here's a link to the docs](https://python-chess.readthedocs.io/). In my mind, we should be working off of `Game` subclass instances, which then have things like the list of moves so far, the legal moves, the current board state, etc.

**Comment by PhilipEkfeldt** [comment]
> Ah, I see what you mean. I'm mostly styling this along the lines of the `python-chess` library because I think it has some great things about it. [Here's a link to the docs](https://python-chess.readthedocs.io/). In my mind, we should be working off of `Game` subclass instances, which then have things like the list of moves so far, the legal moves, the current board state, etc.

Ah nice, I'll check it out! See my other comment #12 for how I imagined it. I'm flexible, just want to avoid unnecessary boilerplate in the mcts implementation.

**Pull request merged**
